name: 🎗　Update Authors
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: bubkoo/update-authors@v1
        with:
          GITHUB_TOKEN: ${{ secrets.bot_token  }}
          bots: false
