name: 🧑‍　Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-assign@v1
        with:
          GITHUB_TOKEN: ${{ secrets.bot_token }}
          CONFIG_FILE: .github/workflows/config/auto-assign.yml
