name: 🤝　Contributors
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.bot_token }}
          svgPath: CONTRIBUTORS.svg
