name: 🏷️　Label(File Paths)
on: pull_request
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.bot_token }}
          configuration-path: .github/workflows/config/pr-label-file-paths.yml
