name: 🏷️　Label(Patch Size)
on: pull_request
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pascalgn/size-label-action@v0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.bot_token }}
          IGNORED: "!.gitignore\nyarn.lock"
